export { createGuard } from './guard.js'
export { PolicyError, ShapeError, CallerError } from '../shared/errors.js'
export type {
  FieldMeta,
  InputOpts,
  ModelOpts,
  QueryMethod,
  MutationMethod,
  ShapeConfig,
  ShapeOrFn,
  NestedIncludeArgs,
  NestedSelectArgs,
  ScopeEntry,
  ScopeMap,
  TypeMap,
  EnumMap,
  ZodChains,
  UniqueConstraint,
  UniqueMap,
  MissingScopeContextMode,
  GuardGeneratedConfig,
  GuardConfig,
  GuardLogger,
  QuerySchema,
  InputSchema,
  GuardShape,
  GuardShapeOrFn,
  GuardInput,
  GuardedModel,
} from '../shared/types.js'